Service:
  name: "users_dashboard"
  path_prefix: ""
  version: "0.0.1"
  debug: false
  port: 8081
Database:
  engine: "mysql"
  host: "localhost"
  name: "users_dashboard_db"
  port: 3306
  user: "root"
  password: "root"
